name: CSU Library Reserve1

on:
  workflow_dispatch:

  schedule:
    - cron: '53 21 * * *'

jobs:
  reserve:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Reserve
      run: |
        user1='${{ secrets.USER1 }}'
        pwd1='${{ secrets.PWD1 }}'
        python3 helper1.py --action 'reserve1' --userid $user1 --password $pwd1
    - name: Commit
      run: |
        git config --global user.email founder.yu@foxmail.com
        git config --global user.name founder-yu
        git add .
        git commit -m "Update library1.log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
