name: CSU Library Reserve

on:
  workflow_dispatch:

  schedule:
    - cron: '50 21 * * *'

jobs:
  reserve:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Reserve
      run: |
        user1='${{ secrets.USER1 }}'
        pwd1='${{ secrets.PWD1 }}'
        user2='${{ secrets.USER2 }}'
        pwd2='${{ secrets.PWD2 }}'
        user3='${{ secrets.USER3 }}'
        pwd3='${{ secrets.PWD3 }}'
        user4='${{ secrets.USER4 }}'
        pwd4='${{ secrets.PWD4 }}'
        python3 helper1.py --action 'reserve' --userid $user1 --password $pwd1
        python3 helper2.py --action 'reserve' --userid $user2 --password $pwd2
        python3 helper3.py --action 'reserve' --userid $user3 --password $pwd3
        python3 helper4.py --action 'reserve' --userid $user4 --password $pwd4
    - name: Commit
      run: |
        git config --global user.email founder.yu@foxmail.com
        git config --global user.name founder-yu
        git add .
        git commit -m "Update library.log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
