name: CSU Library Reserve3

on:
  workflow_dispatch:

  schedule:
    - cron: '50 21 * * *'

jobs:
  reserve:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Reserve
      run: |
        user3='${{ secrets.USER3 }}'
        pwd3='${{ secrets.PWD3 }}'
        python3 helper3.py --action 'reserve3' --userid $user3 --password $pwd3
    - name: Commit
      run: |
        git config --global user.email founder.yu@foxmail.com
        git config --global user.name founder-yu
        git add .
        git commit -m "Update library3.log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
